kind: pipeline
type: kubernetes
name: default

steps:
  - name: get tags
    image: alpine/git
    commands:
      - git describe --abbrev=0 --tag | tr -d '\n' > .tags

  - name: docker
    image: banzaicloud/drone-kaniko
    settings:
      email: kedthunder@gmail.com
      dockerfile: ./Dockerfile
      registry: docker.pkg.github.com
      repo: ked57/mspr-user-api-doc/documentation
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
  - name: deploy
    image: pabloclsn/kubectl-docker:latest
    commands:
      - echo $KUBE_CONFIG > ~/.kube/config
      - cat .kube/deployment.yaml | envsubst | kubectl apply -f -
      - kubectl rollout restart deployment/mspr-user-api-doc-deployment -n prod-mspr-ci
    environment:
      KUBE_CONFIG:
        from_secret: KUBE_CONFIG
trigger:
  branch:
  - master